// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AboutDocumentDataSlicesSlice =
  | AboutMeBlockSlice
  | AboutHeroBlockSlice
  | StatsBlockSlice
  | ItemsBlockSlice;

/**
 * Content for About documents
 */
interface AboutDocumentData {
  /**
   * Slice Zone field in *About*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AboutDocumentDataSlicesSlice> /**
   * Meta Title field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: about.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: about.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *About*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * keywords field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.keywords
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  keywords: prismic.KeyTextField;
}

/**
 * About document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<AboutDocumentData>, "about", Lang>;

type EtcrDocumentDataSlicesSlice =
  | EtcrTextImageBlockSlice
  | AboutCoreLabSlice
  | EtcrHeroBlockSlice;

/**
 * Content for ETCR documents
 */
interface EtcrDocumentData {
  /**
   * Slice Zone field in *ETCR*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: etcr.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<EtcrDocumentDataSlicesSlice> /**
   * Meta Title field in *ETCR*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: etcr.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *ETCR*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: etcr.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *ETCR*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: etcr.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * keywords field in *ETCR*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: etcr.keywords
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  keywords: prismic.KeyTextField;
}

/**
 * ETCR document from Prismic
 *
 * - **API ID**: `etcr`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EtcrDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<EtcrDocumentData>, "etcr", Lang>;

type HomeDocumentDataSlicesSlice =
  | ImageSliderSlice
  | AboutCoreLabSlice
  | HomeHeroBlockSlice
  | AboutHeroBlockSlice
  | ServicesBlockSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type StudentsDocumentDataSlicesSlice =
  | PastStudentsBlockSlice
  | CurrentStudentBlockSlice
  | GalleryBlockSlice
  | StudentHeroBlockSlice;

/**
 * Content for Students documents
 */
interface StudentsDocumentData {
  /**
   * Slice Zone field in *Students*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: students.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<StudentsDocumentDataSlicesSlice> /**
   * Meta Title field in *Students*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: students.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Students*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: students.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Students*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: students.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * keyword field in *Students*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: students.keyword
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  keyword: prismic.KeyTextField;
}

/**
 * Students document from Prismic
 *
 * - **API ID**: `students`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type StudentsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<StudentsDocumentData>,
    "students",
    Lang
  >;

type TeachingDocumentDataSlicesSlice =
  | TeachingHeroBlockSlice
  | CoursesBlockSlice;

/**
 * Content for Teaching documents
 */
interface TeachingDocumentData {
  /**
   * Slice Zone field in *Teaching*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: teaching.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<TeachingDocumentDataSlicesSlice> /**
   * Meta Title field in *Teaching*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: teaching.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Teaching*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: teaching.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Teaching*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: teaching.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * keywords field in *Teaching*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: teaching.keywords
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  keywords: prismic.KeyTextField;
}

/**
 * Teaching document from Prismic
 *
 * - **API ID**: `teaching`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TeachingDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<TeachingDocumentData>,
    "teaching",
    Lang
  >;

export type AllDocumentTypes =
  | AboutDocument
  | EtcrDocument
  | HomeDocument
  | StudentsDocument
  | TeachingDocument;

/**
 * Primary content in *AboutCoreLab → Default → Primary*
 */
export interface AboutCoreLabSliceDefaultPrimary {
  /**
   * title field in *AboutCoreLab → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_core_lab.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * content field in *AboutCoreLab → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_core_lab.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;
}

/**
 * Default variation for AboutCoreLab Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutCoreLabSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutCoreLabSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AboutCoreLab*
 */
type AboutCoreLabSliceVariation = AboutCoreLabSliceDefault;

/**
 * AboutCoreLab Shared Slice
 *
 * - **API ID**: `about_core_lab`
 * - **Description**: AboutCoreLab
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutCoreLabSlice = prismic.SharedSlice<
  "about_core_lab",
  AboutCoreLabSliceVariation
>;

/**
 * Primary content in *AboutHeroBlock → Default → Primary*
 */
export interface AboutHeroBlockSliceDefaultPrimary {
  /**
   * title field in *AboutHeroBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_hero_block.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * content field in *AboutHeroBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_hero_block.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;

  /**
   * image field in *AboutHeroBlock → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_hero_block.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * name field in *AboutHeroBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_hero_block.default.primary.name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * btn text field in *AboutHeroBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_hero_block.default.primary.btn_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  btn_text: prismic.KeyTextField;

  /**
   * btn link field in *AboutHeroBlock → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: about_hero_block.default.primary.btn_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  btn_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for AboutHeroBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutHeroBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutHeroBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AboutHeroBlock*
 */
type AboutHeroBlockSliceVariation = AboutHeroBlockSliceDefault;

/**
 * AboutHeroBlock Shared Slice
 *
 * - **API ID**: `about_hero_block`
 * - **Description**: AboutHeroBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutHeroBlockSlice = prismic.SharedSlice<
  "about_hero_block",
  AboutHeroBlockSliceVariation
>;

/**
 * Item in *AboutMeBlock → Default → Primary → stats*
 */
export interface AboutMeBlockSliceDefaultPrimaryStatsItem {
  /**
   * number field in *AboutMeBlock → Default → Primary → stats*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_me_block.default.primary.stats[].number
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  number: prismic.KeyTextField;

  /**
   * text field in *AboutMeBlock → Default → Primary → stats*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_me_block.default.primary.stats[].text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;
}

/**
 * Primary content in *AboutMeBlock → Default → Primary*
 */
export interface AboutMeBlockSliceDefaultPrimary {
  /**
   * title field in *AboutMeBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_me_block.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * image field in *AboutMeBlock → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_me_block.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * content field in *AboutMeBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_me_block.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;

  /**
   * position field in *AboutMeBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_me_block.default.primary.position
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  position: prismic.KeyTextField;

  /**
   * department field in *AboutMeBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_me_block.default.primary.department
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  department: prismic.KeyTextField;

  /**
   * location field in *AboutMeBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_me_block.default.primary.location
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  location: prismic.KeyTextField;

  /**
   * stats field in *AboutMeBlock → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about_me_block.default.primary.stats[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  stats: prismic.GroupField<Simplify<AboutMeBlockSliceDefaultPrimaryStatsItem>>;
}

/**
 * Default variation for AboutMeBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutMeBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutMeBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AboutMeBlock*
 */
type AboutMeBlockSliceVariation = AboutMeBlockSliceDefault;

/**
 * AboutMeBlock Shared Slice
 *
 * - **API ID**: `about_me_block`
 * - **Description**: AboutMeBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutMeBlockSlice = prismic.SharedSlice<
  "about_me_block",
  AboutMeBlockSliceVariation
>;

/**
 * Item in *CoursesBlock → Default → Primary → courses*
 */
export interface CoursesBlockSliceDefaultPrimaryCoursesItem {
  /**
   * image field in *CoursesBlock → Default → Primary → courses*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: courses_block.default.primary.courses[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * course code field in *CoursesBlock → Default → Primary → courses*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: courses_block.default.primary.courses[].course_code
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  course_code: prismic.KeyTextField;

  /**
   * title field in *CoursesBlock → Default → Primary → courses*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: courses_block.default.primary.courses[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *CoursesBlock → Default → Primary → courses*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: courses_block.default.primary.courses[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Primary content in *CoursesBlock → Default → Primary*
 */
export interface CoursesBlockSliceDefaultPrimary {
  /**
   * courses field in *CoursesBlock → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: courses_block.default.primary.courses[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  courses: prismic.GroupField<
    Simplify<CoursesBlockSliceDefaultPrimaryCoursesItem>
  >;
}

/**
 * Default variation for CoursesBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CoursesBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CoursesBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CoursesBlock*
 */
type CoursesBlockSliceVariation = CoursesBlockSliceDefault;

/**
 * CoursesBlock Shared Slice
 *
 * - **API ID**: `courses_block`
 * - **Description**: CoursesBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CoursesBlockSlice = prismic.SharedSlice<
  "courses_block",
  CoursesBlockSliceVariation
>;

/**
 * Item in *CurrentStudentBlock → Default → Primary → students*
 */
export interface CurrentStudentBlockSliceDefaultPrimaryStudentsItem {
  /**
   * name field in *CurrentStudentBlock → Default → Primary → students*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: current_student_block.default.primary.students[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * image field in *CurrentStudentBlock → Default → Primary → students*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: current_student_block.default.primary.students[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * biography field in *CurrentStudentBlock → Default → Primary → students*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: current_student_block.default.primary.students[].biography
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  biography: prismic.KeyTextField;

  /**
   * graduation year field in *CurrentStudentBlock → Default → Primary → students*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: current_student_block.default.primary.students[].graduation_year
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  graduation_year: prismic.KeyTextField;
}

/**
 * Primary content in *CurrentStudentBlock → Default → Primary*
 */
export interface CurrentStudentBlockSliceDefaultPrimary {
  /**
   * title field in *CurrentStudentBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: current_student_block.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * students field in *CurrentStudentBlock → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: current_student_block.default.primary.students[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  students: prismic.GroupField<
    Simplify<CurrentStudentBlockSliceDefaultPrimaryStudentsItem>
  >;
}

/**
 * Default variation for CurrentStudentBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CurrentStudentBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CurrentStudentBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CurrentStudentBlock*
 */
type CurrentStudentBlockSliceVariation = CurrentStudentBlockSliceDefault;

/**
 * CurrentStudentBlock Shared Slice
 *
 * - **API ID**: `current_student_block`
 * - **Description**: CurrentStudentBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CurrentStudentBlockSlice = prismic.SharedSlice<
  "current_student_block",
  CurrentStudentBlockSliceVariation
>;

/**
 * Primary content in *EtcrHeroBlock → Default → Primary*
 */
export interface EtcrHeroBlockSliceDefaultPrimary {
  /**
   * title field in *EtcrHeroBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: etcr_hero_block.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * image field in *EtcrHeroBlock → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: etcr_hero_block.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * content field in *EtcrHeroBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: etcr_hero_block.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;

  /**
   * btn text field in *EtcrHeroBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: etcr_hero_block.default.primary.btn_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  btn_text: prismic.KeyTextField;

  /**
   * btn url field in *EtcrHeroBlock → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: etcr_hero_block.default.primary.btn_url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  btn_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for EtcrHeroBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EtcrHeroBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EtcrHeroBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *EtcrHeroBlock*
 */
type EtcrHeroBlockSliceVariation = EtcrHeroBlockSliceDefault;

/**
 * EtcrHeroBlock Shared Slice
 *
 * - **API ID**: `etcr_hero_block`
 * - **Description**: EtcrHeroBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EtcrHeroBlockSlice = prismic.SharedSlice<
  "etcr_hero_block",
  EtcrHeroBlockSliceVariation
>;

/**
 * Item in *EtcrTextImageBlock → Default → Primary → images*
 */
export interface EtcrTextImageBlockSliceDefaultPrimaryImagesItem {
  /**
   * image field in *EtcrTextImageBlock → Default → Primary → images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: etcr_text_image_block.default.primary.images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *EtcrTextImageBlock → Default → Primary*
 */
export interface EtcrTextImageBlockSliceDefaultPrimary {
  /**
   * title field in *EtcrTextImageBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: etcr_text_image_block.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * text_one field in *EtcrTextImageBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: etcr_text_image_block.default.primary.text_one
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text_one: prismic.KeyTextField;

  /**
   * text_two field in *EtcrTextImageBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: etcr_text_image_block.default.primary.text_two
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text_two: prismic.KeyTextField;

  /**
   * text_three field in *EtcrTextImageBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: etcr_text_image_block.default.primary.text_three
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text_three: prismic.KeyTextField;

  /**
   * text_four field in *EtcrTextImageBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: etcr_text_image_block.default.primary.text_four
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text_four: prismic.KeyTextField;

  /**
   * images field in *EtcrTextImageBlock → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: etcr_text_image_block.default.primary.images[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<
    Simplify<EtcrTextImageBlockSliceDefaultPrimaryImagesItem>
  >;
}

/**
 * Default variation for EtcrTextImageBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EtcrTextImageBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EtcrTextImageBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *EtcrTextImageBlock*
 */
type EtcrTextImageBlockSliceVariation = EtcrTextImageBlockSliceDefault;

/**
 * EtcrTextImageBlock Shared Slice
 *
 * - **API ID**: `etcr_text_image_block`
 * - **Description**: EtcrTextImageBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EtcrTextImageBlockSlice = prismic.SharedSlice<
  "etcr_text_image_block",
  EtcrTextImageBlockSliceVariation
>;

/**
 * Item in *GalleryBlock → Default → Primary → images*
 */
export interface GalleryBlockSliceDefaultPrimaryImagesItem {
  /**
   * image field in *GalleryBlock → Default → Primary → images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_block.default.primary.images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *GalleryBlock → Default → Primary*
 */
export interface GalleryBlockSliceDefaultPrimary {
  /**
   * title field in *GalleryBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_block.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * images field in *GalleryBlock → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_block.default.primary.images[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<
    Simplify<GalleryBlockSliceDefaultPrimaryImagesItem>
  >;
}

/**
 * Default variation for GalleryBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GalleryBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GalleryBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *GalleryBlock*
 */
type GalleryBlockSliceVariation = GalleryBlockSliceDefault;

/**
 * GalleryBlock Shared Slice
 *
 * - **API ID**: `gallery_block`
 * - **Description**: GalleryBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GalleryBlockSlice = prismic.SharedSlice<
  "gallery_block",
  GalleryBlockSliceVariation
>;

/**
 * Primary content in *HeroBlock → Default → Primary*
 */
export interface HeroBlockSliceDefaultPrimary {
  /**
   * title field in *HeroBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_block.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * content field in *HeroBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_block.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;
}

/**
 * Default variation for HeroBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroBlock*
 */
type HeroBlockSliceVariation = HeroBlockSliceDefault;

/**
 * HeroBlock Shared Slice
 *
 * - **API ID**: `hero_block`
 * - **Description**: HeroBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroBlockSlice = prismic.SharedSlice<
  "hero_block",
  HeroBlockSliceVariation
>;

/**
 * Item in *HomeHeroBlock → Default → Primary → images*
 */
export interface HomeHeroBlockSliceDefaultPrimaryImagesItem {
  /**
   * image field in *HomeHeroBlock → Default → Primary → images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_hero_block.default.primary.images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *HomeHeroBlock → Default → Primary*
 */
export interface HomeHeroBlockSliceDefaultPrimary {
  /**
   * image field in *HomeHeroBlock → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_hero_block.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * title field in *HomeHeroBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_hero_block.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * content field in *HomeHeroBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_hero_block.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;

  /**
   * btn text field in *HomeHeroBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_hero_block.default.primary.btn_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  btn_text: prismic.KeyTextField;

  /**
   * btn link field in *HomeHeroBlock → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home_hero_block.default.primary.btn_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  btn_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * images field in *HomeHeroBlock → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home_hero_block.default.primary.images[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<
    Simplify<HomeHeroBlockSliceDefaultPrimaryImagesItem>
  >;
}

/**
 * Default variation for HomeHeroBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeHeroBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HomeHeroBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HomeHeroBlock*
 */
type HomeHeroBlockSliceVariation = HomeHeroBlockSliceDefault;

/**
 * HomeHeroBlock Shared Slice
 *
 * - **API ID**: `home_hero_block`
 * - **Description**: HomeHeroBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeHeroBlockSlice = prismic.SharedSlice<
  "home_hero_block",
  HomeHeroBlockSliceVariation
>;

/**
 * Item in *ImageSlider → Default → Primary → images*
 */
export interface ImageSliderSliceDefaultPrimaryImagesItem {
  /**
   * image field in *ImageSlider → Default → Primary → images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_slider.default.primary.images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * caption field in *ImageSlider → Default → Primary → images*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_slider.default.primary.images[].caption
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  caption: prismic.KeyTextField;
}

/**
 * Primary content in *ImageSlider → Default → Primary*
 */
export interface ImageSliderSliceDefaultPrimary {
  /**
   * title field in *ImageSlider → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_slider.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * images field in *ImageSlider → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: image_slider.default.primary.images[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<
    Simplify<ImageSliderSliceDefaultPrimaryImagesItem>
  >;
}

/**
 * Default variation for ImageSlider Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageSliderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ImageSlider*
 */
type ImageSliderSliceVariation = ImageSliderSliceDefault;

/**
 * ImageSlider Shared Slice
 *
 * - **API ID**: `image_slider`
 * - **Description**: ImageSlider
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliderSlice = prismic.SharedSlice<
  "image_slider",
  ImageSliderSliceVariation
>;

/**
 * Item in *ItemsBlock → Default → Primary → publications*
 */
export interface ItemsBlockSliceDefaultPrimaryPublicationsItem {
  /**
   * text field in *ItemsBlock → Default → Primary → publications*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: items_block.default.primary.publications[].text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;
}

/**
 * Item in *ItemsBlock → Default → Primary → events*
 */
export interface ItemsBlockSliceDefaultPrimaryEventsItem {
  /**
   * text field in *ItemsBlock → Default → Primary → events*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: items_block.default.primary.events[].text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;
}

/**
 * Item in *ItemsBlock → Default → Primary → awards*
 */
export interface ItemsBlockSliceDefaultPrimaryAwardsItem {
  /**
   * text field in *ItemsBlock → Default → Primary → awards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: items_block.default.primary.awards[].text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;
}

/**
 * Primary content in *ItemsBlock → Default → Primary*
 */
export interface ItemsBlockSliceDefaultPrimary {
  /**
   * publication text field in *ItemsBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: items_block.default.primary.publication_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  publication_text: prismic.KeyTextField;

  /**
   * publications field in *ItemsBlock → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: items_block.default.primary.publications[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  publications: prismic.GroupField<
    Simplify<ItemsBlockSliceDefaultPrimaryPublicationsItem>
  >;

  /**
   * events title field in *ItemsBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: items_block.default.primary.events_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  events_title: prismic.KeyTextField;

  /**
   * events field in *ItemsBlock → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: items_block.default.primary.events[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  events: prismic.GroupField<Simplify<ItemsBlockSliceDefaultPrimaryEventsItem>>;

  /**
   * awards text field in *ItemsBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: items_block.default.primary.awards_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  awards_text: prismic.KeyTextField;

  /**
   * awards field in *ItemsBlock → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: items_block.default.primary.awards[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  awards: prismic.GroupField<Simplify<ItemsBlockSliceDefaultPrimaryAwardsItem>>;
}

/**
 * Default variation for ItemsBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ItemsBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ItemsBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ItemsBlock*
 */
type ItemsBlockSliceVariation = ItemsBlockSliceDefault;

/**
 * ItemsBlock Shared Slice
 *
 * - **API ID**: `items_block`
 * - **Description**: ItemsBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ItemsBlockSlice = prismic.SharedSlice<
  "items_block",
  ItemsBlockSliceVariation
>;

/**
 * Item in *PastStudentsBlock → Default → Primary → students*
 */
export interface PastStudentsBlockSliceDefaultPrimaryStudentsItem {
  /**
   * image field in *PastStudentsBlock → Default → Primary → students*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: past_students_block.default.primary.students[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * name field in *PastStudentsBlock → Default → Primary → students*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: past_students_block.default.primary.students[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * graduation year field in *PastStudentsBlock → Default → Primary → students*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: past_students_block.default.primary.students[].graduation_year
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  graduation_year: prismic.KeyTextField;

  /**
   * project link field in *PastStudentsBlock → Default → Primary → students*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: past_students_block.default.primary.students[].project_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  project_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * bio field in *PastStudentsBlock → Default → Primary → students*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: past_students_block.default.primary.students[].bio
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  bio: prismic.KeyTextField;
}

/**
 * Primary content in *PastStudentsBlock → Default → Primary*
 */
export interface PastStudentsBlockSliceDefaultPrimary {
  /**
   * title field in *PastStudentsBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: past_students_block.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * students field in *PastStudentsBlock → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: past_students_block.default.primary.students[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  students: prismic.GroupField<
    Simplify<PastStudentsBlockSliceDefaultPrimaryStudentsItem>
  >;
}

/**
 * Default variation for PastStudentsBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PastStudentsBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PastStudentsBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PastStudentsBlock*
 */
type PastStudentsBlockSliceVariation = PastStudentsBlockSliceDefault;

/**
 * PastStudentsBlock Shared Slice
 *
 * - **API ID**: `past_students_block`
 * - **Description**: PastStudentsBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PastStudentsBlockSlice = prismic.SharedSlice<
  "past_students_block",
  PastStudentsBlockSliceVariation
>;

/**
 * Item in *ServicesBlock → Default → Primary → services*
 */
export interface ServicesBlockSliceDefaultPrimaryServicesItem {
  /**
   * bg image field in *ServicesBlock → Default → Primary → services*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services_block.default.primary.services[].bg_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  bg_image: prismic.ImageField<never>;

  /**
   * icon field in *ServicesBlock → Default → Primary → services*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services_block.default.primary.services[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * title field in *ServicesBlock → Default → Primary → services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_block.default.primary.services[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * content field in *ServicesBlock → Default → Primary → services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_block.default.primary.services[].content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;

  /**
   * btn text field in *ServicesBlock → Default → Primary → services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_block.default.primary.services[].btn_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  btn_text: prismic.KeyTextField;

  /**
   * btn link field in *ServicesBlock → Default → Primary → services*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: services_block.default.primary.services[].btn_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  btn_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *ServicesBlock → Default → Primary*
 */
export interface ServicesBlockSliceDefaultPrimary {
  /**
   * title field in *ServicesBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_block.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * services field in *ServicesBlock → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: services_block.default.primary.services[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  services: prismic.GroupField<
    Simplify<ServicesBlockSliceDefaultPrimaryServicesItem>
  >;
}

/**
 * Default variation for ServicesBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServicesBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ServicesBlock*
 */
type ServicesBlockSliceVariation = ServicesBlockSliceDefault;

/**
 * ServicesBlock Shared Slice
 *
 * - **API ID**: `services_block`
 * - **Description**: ServicesBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesBlockSlice = prismic.SharedSlice<
  "services_block",
  ServicesBlockSliceVariation
>;

/**
 * Item in *StatsBlock → Default → Primary → stats*
 */
export interface StatsBlockSliceDefaultPrimaryStatsItem {
  /**
   * number field in *StatsBlock → Default → Primary → stats*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: stats_block.default.primary.stats[].number
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  number: prismic.KeyTextField;

  /**
   * text field in *StatsBlock → Default → Primary → stats*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: stats_block.default.primary.stats[].text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;
}

/**
 * Primary content in *StatsBlock → Default → Primary*
 */
export interface StatsBlockSliceDefaultPrimary {
  /**
   * stats field in *StatsBlock → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: stats_block.default.primary.stats[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  stats: prismic.GroupField<Simplify<StatsBlockSliceDefaultPrimaryStatsItem>>;
}

/**
 * Default variation for StatsBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StatsBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StatsBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *StatsBlock*
 */
type StatsBlockSliceVariation = StatsBlockSliceDefault;

/**
 * StatsBlock Shared Slice
 *
 * - **API ID**: `stats_block`
 * - **Description**: StatsBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StatsBlockSlice = prismic.SharedSlice<
  "stats_block",
  StatsBlockSliceVariation
>;

/**
 * Item in *StudentHeroBlock → Default → Primary → images*
 */
export interface StudentHeroBlockSliceDefaultPrimaryImagesItem {
  /**
   * image field in *StudentHeroBlock → Default → Primary → images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: student_hero_block.default.primary.images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *StudentHeroBlock → Default → Primary*
 */
export interface StudentHeroBlockSliceDefaultPrimary {
  /**
   * title field in *StudentHeroBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: student_hero_block.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * image field in *StudentHeroBlock → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: student_hero_block.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * content field in *StudentHeroBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: student_hero_block.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;

  /**
   * images field in *StudentHeroBlock → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: student_hero_block.default.primary.images[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<
    Simplify<StudentHeroBlockSliceDefaultPrimaryImagesItem>
  >;

  /**
   * btn text field in *StudentHeroBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: student_hero_block.default.primary.btn_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  btn_text: prismic.KeyTextField;

  /**
   * btn link field in *StudentHeroBlock → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: student_hero_block.default.primary.btn_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  btn_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for StudentHeroBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StudentHeroBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StudentHeroBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *StudentHeroBlock*
 */
type StudentHeroBlockSliceVariation = StudentHeroBlockSliceDefault;

/**
 * StudentHeroBlock Shared Slice
 *
 * - **API ID**: `student_hero_block`
 * - **Description**: StudentHeroBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StudentHeroBlockSlice = prismic.SharedSlice<
  "student_hero_block",
  StudentHeroBlockSliceVariation
>;

/**
 * Primary content in *TeachingHeroBlock → Default → Primary*
 */
export interface TeachingHeroBlockSliceDefaultPrimary {
  /**
   * title field in *TeachingHeroBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: teaching_hero_block.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * content field in *TeachingHeroBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: teaching_hero_block.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;
}

/**
 * Default variation for TeachingHeroBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeachingHeroBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TeachingHeroBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TeachingHeroBlock*
 */
type TeachingHeroBlockSliceVariation = TeachingHeroBlockSliceDefault;

/**
 * TeachingHeroBlock Shared Slice
 *
 * - **API ID**: `teaching_hero_block`
 * - **Description**: TeachingHeroBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeachingHeroBlockSlice = prismic.SharedSlice<
  "teaching_hero_block",
  TeachingHeroBlockSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutDocument,
      AboutDocumentData,
      AboutDocumentDataSlicesSlice,
      EtcrDocument,
      EtcrDocumentData,
      EtcrDocumentDataSlicesSlice,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      StudentsDocument,
      StudentsDocumentData,
      StudentsDocumentDataSlicesSlice,
      TeachingDocument,
      TeachingDocumentData,
      TeachingDocumentDataSlicesSlice,
      AllDocumentTypes,
      AboutCoreLabSlice,
      AboutCoreLabSliceDefaultPrimary,
      AboutCoreLabSliceVariation,
      AboutCoreLabSliceDefault,
      AboutHeroBlockSlice,
      AboutHeroBlockSliceDefaultPrimary,
      AboutHeroBlockSliceVariation,
      AboutHeroBlockSliceDefault,
      AboutMeBlockSlice,
      AboutMeBlockSliceDefaultPrimaryStatsItem,
      AboutMeBlockSliceDefaultPrimary,
      AboutMeBlockSliceVariation,
      AboutMeBlockSliceDefault,
      CoursesBlockSlice,
      CoursesBlockSliceDefaultPrimaryCoursesItem,
      CoursesBlockSliceDefaultPrimary,
      CoursesBlockSliceVariation,
      CoursesBlockSliceDefault,
      CurrentStudentBlockSlice,
      CurrentStudentBlockSliceDefaultPrimaryStudentsItem,
      CurrentStudentBlockSliceDefaultPrimary,
      CurrentStudentBlockSliceVariation,
      CurrentStudentBlockSliceDefault,
      EtcrHeroBlockSlice,
      EtcrHeroBlockSliceDefaultPrimary,
      EtcrHeroBlockSliceVariation,
      EtcrHeroBlockSliceDefault,
      EtcrTextImageBlockSlice,
      EtcrTextImageBlockSliceDefaultPrimaryImagesItem,
      EtcrTextImageBlockSliceDefaultPrimary,
      EtcrTextImageBlockSliceVariation,
      EtcrTextImageBlockSliceDefault,
      GalleryBlockSlice,
      GalleryBlockSliceDefaultPrimaryImagesItem,
      GalleryBlockSliceDefaultPrimary,
      GalleryBlockSliceVariation,
      GalleryBlockSliceDefault,
      HeroBlockSlice,
      HeroBlockSliceDefaultPrimary,
      HeroBlockSliceVariation,
      HeroBlockSliceDefault,
      HomeHeroBlockSlice,
      HomeHeroBlockSliceDefaultPrimaryImagesItem,
      HomeHeroBlockSliceDefaultPrimary,
      HomeHeroBlockSliceVariation,
      HomeHeroBlockSliceDefault,
      ImageSliderSlice,
      ImageSliderSliceDefaultPrimaryImagesItem,
      ImageSliderSliceDefaultPrimary,
      ImageSliderSliceVariation,
      ImageSliderSliceDefault,
      ItemsBlockSlice,
      ItemsBlockSliceDefaultPrimaryPublicationsItem,
      ItemsBlockSliceDefaultPrimaryEventsItem,
      ItemsBlockSliceDefaultPrimaryAwardsItem,
      ItemsBlockSliceDefaultPrimary,
      ItemsBlockSliceVariation,
      ItemsBlockSliceDefault,
      PastStudentsBlockSlice,
      PastStudentsBlockSliceDefaultPrimaryStudentsItem,
      PastStudentsBlockSliceDefaultPrimary,
      PastStudentsBlockSliceVariation,
      PastStudentsBlockSliceDefault,
      ServicesBlockSlice,
      ServicesBlockSliceDefaultPrimaryServicesItem,
      ServicesBlockSliceDefaultPrimary,
      ServicesBlockSliceVariation,
      ServicesBlockSliceDefault,
      StatsBlockSlice,
      StatsBlockSliceDefaultPrimaryStatsItem,
      StatsBlockSliceDefaultPrimary,
      StatsBlockSliceVariation,
      StatsBlockSliceDefault,
      StudentHeroBlockSlice,
      StudentHeroBlockSliceDefaultPrimaryImagesItem,
      StudentHeroBlockSliceDefaultPrimary,
      StudentHeroBlockSliceVariation,
      StudentHeroBlockSliceDefault,
      TeachingHeroBlockSlice,
      TeachingHeroBlockSliceDefaultPrimary,
      TeachingHeroBlockSliceVariation,
      TeachingHeroBlockSliceDefault,
    };
  }
}
