// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AboutDocumentDataSlicesSlice =
  | AboutMeBlockSlice
  | AboutHeroBlockSlice
  | StatsBlockSlice
  | ItemsBlockSlice;

/**
 * Content for About documents
 */
interface AboutDocumentData {
  /**
   * Slice Zone field in *About*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AboutDocumentDataSlicesSlice> /**
   * Meta Title field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: about.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: about.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *About*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * keywords field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.keywords
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  keywords: prismic.KeyTextField;
}

/**
 * About document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<AboutDocumentData>, "about", Lang>;

type HomeDocumentDataSlicesSlice =
  | HomeStudentsBlockSlice
  | AboutHeroBlockSlice
  | ServicesBlockSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type StudentsDocumentDataSlicesSlice =
  | GalleryBlockSlice
  | StudentHeroBlockSlice;

/**
 * Content for Students documents
 */
interface StudentsDocumentData {
  /**
   * Slice Zone field in *Students*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: students.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<StudentsDocumentDataSlicesSlice> /**
   * Meta Title field in *Students*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: students.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Students*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: students.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Students*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: students.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * keyword field in *Students*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: students.keyword
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  keyword: prismic.KeyTextField;
}

/**
 * Students document from Prismic
 *
 * - **API ID**: `students`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type StudentsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<StudentsDocumentData>,
    "students",
    Lang
  >;

export type AllDocumentTypes = AboutDocument | HomeDocument | StudentsDocument;

/**
 * Primary content in *AboutHeroBlock → Default → Primary*
 */
export interface AboutHeroBlockSliceDefaultPrimary {
  /**
   * title field in *AboutHeroBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_hero_block.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * content field in *AboutHeroBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_hero_block.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;

  /**
   * image field in *AboutHeroBlock → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_hero_block.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * name field in *AboutHeroBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_hero_block.default.primary.name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * btn text field in *AboutHeroBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_hero_block.default.primary.btn_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  btn_text: prismic.KeyTextField;

  /**
   * btn link field in *AboutHeroBlock → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: about_hero_block.default.primary.btn_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  btn_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for AboutHeroBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutHeroBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutHeroBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AboutHeroBlock*
 */
type AboutHeroBlockSliceVariation = AboutHeroBlockSliceDefault;

/**
 * AboutHeroBlock Shared Slice
 *
 * - **API ID**: `about_hero_block`
 * - **Description**: AboutHeroBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutHeroBlockSlice = prismic.SharedSlice<
  "about_hero_block",
  AboutHeroBlockSliceVariation
>;

/**
 * Item in *AboutMeBlock → Default → Primary → stats*
 */
export interface AboutMeBlockSliceDefaultPrimaryStatsItem {
  /**
   * number field in *AboutMeBlock → Default → Primary → stats*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_me_block.default.primary.stats[].number
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  number: prismic.KeyTextField;

  /**
   * text field in *AboutMeBlock → Default → Primary → stats*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_me_block.default.primary.stats[].text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;
}

/**
 * Primary content in *AboutMeBlock → Default → Primary*
 */
export interface AboutMeBlockSliceDefaultPrimary {
  /**
   * title field in *AboutMeBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_me_block.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * image field in *AboutMeBlock → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_me_block.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * content field in *AboutMeBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_me_block.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;

  /**
   * position field in *AboutMeBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_me_block.default.primary.position
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  position: prismic.KeyTextField;

  /**
   * department field in *AboutMeBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_me_block.default.primary.department
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  department: prismic.KeyTextField;

  /**
   * location field in *AboutMeBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_me_block.default.primary.location
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  location: prismic.KeyTextField;

  /**
   * stats field in *AboutMeBlock → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about_me_block.default.primary.stats[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  stats: prismic.GroupField<Simplify<AboutMeBlockSliceDefaultPrimaryStatsItem>>;
}

/**
 * Default variation for AboutMeBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutMeBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutMeBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AboutMeBlock*
 */
type AboutMeBlockSliceVariation = AboutMeBlockSliceDefault;

/**
 * AboutMeBlock Shared Slice
 *
 * - **API ID**: `about_me_block`
 * - **Description**: AboutMeBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutMeBlockSlice = prismic.SharedSlice<
  "about_me_block",
  AboutMeBlockSliceVariation
>;

/**
 * Item in *GalleryBlock → Default → Primary → images*
 */
export interface GalleryBlockSliceDefaultPrimaryImagesItem {
  /**
   * image field in *GalleryBlock → Default → Primary → images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_block.default.primary.images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *GalleryBlock → Default → Primary*
 */
export interface GalleryBlockSliceDefaultPrimary {
  /**
   * title field in *GalleryBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_block.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * images field in *GalleryBlock → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_block.default.primary.images[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<
    Simplify<GalleryBlockSliceDefaultPrimaryImagesItem>
  >;
}

/**
 * Default variation for GalleryBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GalleryBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GalleryBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *GalleryBlock*
 */
type GalleryBlockSliceVariation = GalleryBlockSliceDefault;

/**
 * GalleryBlock Shared Slice
 *
 * - **API ID**: `gallery_block`
 * - **Description**: GalleryBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GalleryBlockSlice = prismic.SharedSlice<
  "gallery_block",
  GalleryBlockSliceVariation
>;

/**
 * Primary content in *HeroBlock → Default → Primary*
 */
export interface HeroBlockSliceDefaultPrimary {
  /**
   * title field in *HeroBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_block.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * content field in *HeroBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_block.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;
}

/**
 * Default variation for HeroBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroBlock*
 */
type HeroBlockSliceVariation = HeroBlockSliceDefault;

/**
 * HeroBlock Shared Slice
 *
 * - **API ID**: `hero_block`
 * - **Description**: HeroBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroBlockSlice = prismic.SharedSlice<
  "hero_block",
  HeroBlockSliceVariation
>;

/**
 * Item in *HomeStudentsBlock → Default → Primary → students*
 */
export interface HomeStudentsBlockSliceDefaultPrimaryStudentsItem {
  /**
   * name field in *HomeStudentsBlock → Default → Primary → students*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_students_block.default.primary.students[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * thesis field in *HomeStudentsBlock → Default → Primary → students*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_students_block.default.primary.students[].thesis
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  thesis: prismic.KeyTextField;
}

/**
 * Primary content in *HomeStudentsBlock → Default → Primary*
 */
export interface HomeStudentsBlockSliceDefaultPrimary {
  /**
   * title field in *HomeStudentsBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_students_block.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * students field in *HomeStudentsBlock → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home_students_block.default.primary.students[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  students: prismic.GroupField<
    Simplify<HomeStudentsBlockSliceDefaultPrimaryStudentsItem>
  >;
}

/**
 * Default variation for HomeStudentsBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeStudentsBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HomeStudentsBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HomeStudentsBlock*
 */
type HomeStudentsBlockSliceVariation = HomeStudentsBlockSliceDefault;

/**
 * HomeStudentsBlock Shared Slice
 *
 * - **API ID**: `home_students_block`
 * - **Description**: HomeStudentsBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeStudentsBlockSlice = prismic.SharedSlice<
  "home_students_block",
  HomeStudentsBlockSliceVariation
>;

/**
 * Item in *ItemsBlock → Default → Primary → publications*
 */
export interface ItemsBlockSliceDefaultPrimaryPublicationsItem {
  /**
   * text field in *ItemsBlock → Default → Primary → publications*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: items_block.default.primary.publications[].text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;
}

/**
 * Item in *ItemsBlock → Default → Primary → events*
 */
export interface ItemsBlockSliceDefaultPrimaryEventsItem {
  /**
   * text field in *ItemsBlock → Default → Primary → events*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: items_block.default.primary.events[].text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;
}

/**
 * Item in *ItemsBlock → Default → Primary → awards*
 */
export interface ItemsBlockSliceDefaultPrimaryAwardsItem {
  /**
   * text field in *ItemsBlock → Default → Primary → awards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: items_block.default.primary.awards[].text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;
}

/**
 * Primary content in *ItemsBlock → Default → Primary*
 */
export interface ItemsBlockSliceDefaultPrimary {
  /**
   * publication text field in *ItemsBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: items_block.default.primary.publication_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  publication_text: prismic.KeyTextField;

  /**
   * publications field in *ItemsBlock → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: items_block.default.primary.publications[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  publications: prismic.GroupField<
    Simplify<ItemsBlockSliceDefaultPrimaryPublicationsItem>
  >;

  /**
   * events title field in *ItemsBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: items_block.default.primary.events_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  events_title: prismic.KeyTextField;

  /**
   * events field in *ItemsBlock → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: items_block.default.primary.events[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  events: prismic.GroupField<Simplify<ItemsBlockSliceDefaultPrimaryEventsItem>>;

  /**
   * awards text field in *ItemsBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: items_block.default.primary.awards_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  awards_text: prismic.KeyTextField;

  /**
   * awards field in *ItemsBlock → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: items_block.default.primary.awards[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  awards: prismic.GroupField<Simplify<ItemsBlockSliceDefaultPrimaryAwardsItem>>;
}

/**
 * Default variation for ItemsBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ItemsBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ItemsBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ItemsBlock*
 */
type ItemsBlockSliceVariation = ItemsBlockSliceDefault;

/**
 * ItemsBlock Shared Slice
 *
 * - **API ID**: `items_block`
 * - **Description**: ItemsBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ItemsBlockSlice = prismic.SharedSlice<
  "items_block",
  ItemsBlockSliceVariation
>;

/**
 * Item in *ServicesBlock → Default → Primary → services*
 */
export interface ServicesBlockSliceDefaultPrimaryServicesItem {
  /**
   * bg image field in *ServicesBlock → Default → Primary → services*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services_block.default.primary.services[].bg_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  bg_image: prismic.ImageField<never>;

  /**
   * icon field in *ServicesBlock → Default → Primary → services*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services_block.default.primary.services[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * title field in *ServicesBlock → Default → Primary → services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_block.default.primary.services[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * content field in *ServicesBlock → Default → Primary → services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_block.default.primary.services[].content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;

  /**
   * btn text field in *ServicesBlock → Default → Primary → services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_block.default.primary.services[].btn_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  btn_text: prismic.KeyTextField;

  /**
   * btn link field in *ServicesBlock → Default → Primary → services*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: services_block.default.primary.services[].btn_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  btn_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *ServicesBlock → Default → Primary*
 */
export interface ServicesBlockSliceDefaultPrimary {
  /**
   * title field in *ServicesBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_block.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * services field in *ServicesBlock → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: services_block.default.primary.services[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  services: prismic.GroupField<
    Simplify<ServicesBlockSliceDefaultPrimaryServicesItem>
  >;
}

/**
 * Default variation for ServicesBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServicesBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ServicesBlock*
 */
type ServicesBlockSliceVariation = ServicesBlockSliceDefault;

/**
 * ServicesBlock Shared Slice
 *
 * - **API ID**: `services_block`
 * - **Description**: ServicesBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesBlockSlice = prismic.SharedSlice<
  "services_block",
  ServicesBlockSliceVariation
>;

/**
 * Item in *StatsBlock → Default → Primary → stats*
 */
export interface StatsBlockSliceDefaultPrimaryStatsItem {
  /**
   * number field in *StatsBlock → Default → Primary → stats*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: stats_block.default.primary.stats[].number
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  number: prismic.KeyTextField;

  /**
   * text field in *StatsBlock → Default → Primary → stats*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: stats_block.default.primary.stats[].text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;
}

/**
 * Primary content in *StatsBlock → Default → Primary*
 */
export interface StatsBlockSliceDefaultPrimary {
  /**
   * stats field in *StatsBlock → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: stats_block.default.primary.stats[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  stats: prismic.GroupField<Simplify<StatsBlockSliceDefaultPrimaryStatsItem>>;
}

/**
 * Default variation for StatsBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StatsBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StatsBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *StatsBlock*
 */
type StatsBlockSliceVariation = StatsBlockSliceDefault;

/**
 * StatsBlock Shared Slice
 *
 * - **API ID**: `stats_block`
 * - **Description**: StatsBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StatsBlockSlice = prismic.SharedSlice<
  "stats_block",
  StatsBlockSliceVariation
>;

/**
 * Item in *StudentHeroBlock → Default → Primary → images*
 */
export interface StudentHeroBlockSliceDefaultPrimaryImagesItem {
  /**
   * image field in *StudentHeroBlock → Default → Primary → images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: student_hero_block.default.primary.images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *StudentHeroBlock → Default → Primary*
 */
export interface StudentHeroBlockSliceDefaultPrimary {
  /**
   * title field in *StudentHeroBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: student_hero_block.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * image field in *StudentHeroBlock → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: student_hero_block.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * content field in *StudentHeroBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: student_hero_block.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;

  /**
   * images field in *StudentHeroBlock → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: student_hero_block.default.primary.images[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<
    Simplify<StudentHeroBlockSliceDefaultPrimaryImagesItem>
  >;

  /**
   * btn text field in *StudentHeroBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: student_hero_block.default.primary.btn_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  btn_text: prismic.KeyTextField;

  /**
   * btn link field in *StudentHeroBlock → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: student_hero_block.default.primary.btn_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  btn_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for StudentHeroBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StudentHeroBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StudentHeroBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *StudentHeroBlock*
 */
type StudentHeroBlockSliceVariation = StudentHeroBlockSliceDefault;

/**
 * StudentHeroBlock Shared Slice
 *
 * - **API ID**: `student_hero_block`
 * - **Description**: StudentHeroBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StudentHeroBlockSlice = prismic.SharedSlice<
  "student_hero_block",
  StudentHeroBlockSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutDocument,
      AboutDocumentData,
      AboutDocumentDataSlicesSlice,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      StudentsDocument,
      StudentsDocumentData,
      StudentsDocumentDataSlicesSlice,
      AllDocumentTypes,
      AboutHeroBlockSlice,
      AboutHeroBlockSliceDefaultPrimary,
      AboutHeroBlockSliceVariation,
      AboutHeroBlockSliceDefault,
      AboutMeBlockSlice,
      AboutMeBlockSliceDefaultPrimaryStatsItem,
      AboutMeBlockSliceDefaultPrimary,
      AboutMeBlockSliceVariation,
      AboutMeBlockSliceDefault,
      GalleryBlockSlice,
      GalleryBlockSliceDefaultPrimaryImagesItem,
      GalleryBlockSliceDefaultPrimary,
      GalleryBlockSliceVariation,
      GalleryBlockSliceDefault,
      HeroBlockSlice,
      HeroBlockSliceDefaultPrimary,
      HeroBlockSliceVariation,
      HeroBlockSliceDefault,
      HomeStudentsBlockSlice,
      HomeStudentsBlockSliceDefaultPrimaryStudentsItem,
      HomeStudentsBlockSliceDefaultPrimary,
      HomeStudentsBlockSliceVariation,
      HomeStudentsBlockSliceDefault,
      ItemsBlockSlice,
      ItemsBlockSliceDefaultPrimaryPublicationsItem,
      ItemsBlockSliceDefaultPrimaryEventsItem,
      ItemsBlockSliceDefaultPrimaryAwardsItem,
      ItemsBlockSliceDefaultPrimary,
      ItemsBlockSliceVariation,
      ItemsBlockSliceDefault,
      ServicesBlockSlice,
      ServicesBlockSliceDefaultPrimaryServicesItem,
      ServicesBlockSliceDefaultPrimary,
      ServicesBlockSliceVariation,
      ServicesBlockSliceDefault,
      StatsBlockSlice,
      StatsBlockSliceDefaultPrimaryStatsItem,
      StatsBlockSliceDefaultPrimary,
      StatsBlockSliceVariation,
      StatsBlockSliceDefault,
      StudentHeroBlockSlice,
      StudentHeroBlockSliceDefaultPrimaryImagesItem,
      StudentHeroBlockSliceDefaultPrimary,
      StudentHeroBlockSliceVariation,
      StudentHeroBlockSliceDefault,
    };
  }
}
