// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AboutDocumentDataSlicesSlice = ItemsBlockSlice;

/**
 * Content for About documents
 */
interface AboutDocumentData {
  /**
   * Slice Zone field in *About*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AboutDocumentDataSlicesSlice> /**
   * Meta Title field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: about.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: about.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *About*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * keywords field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.keywords
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  keywords: prismic.KeyTextField;
}

/**
 * About document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<AboutDocumentData>, "about", Lang>;

/**
 * Item in *Publications → publications*
 */
export interface PublicationsDocumentDataPublicationsItem {
  /**
   * reference field in *Publications → publications*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: publications.publications[].reference
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  reference: prismic.KeyTextField;
}

/**
 * Content for Publications documents
 */
interface PublicationsDocumentData {
  /**
   * title field in *Publications*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: publications.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * publications field in *Publications*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: publications.publications[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  publications: prismic.GroupField<
    Simplify<PublicationsDocumentDataPublicationsItem>
  >;
}

/**
 * Publications document from Prismic
 *
 * - **API ID**: `publications`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PublicationsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<PublicationsDocumentData>,
    "publications",
    Lang
  >;

export type AllDocumentTypes = AboutDocument | PublicationsDocument;

/**
 * Item in *ItemsBlock → Default → Primary → publications*
 */
export interface ItemsBlockSliceDefaultPrimaryPublicationsItem {
  /**
   * text field in *ItemsBlock → Default → Primary → publications*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: items_block.default.primary.publications[].text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;
}

/**
 * Item in *ItemsBlock → Default → Primary → events*
 */
export interface ItemsBlockSliceDefaultPrimaryEventsItem {
  /**
   * text field in *ItemsBlock → Default → Primary → events*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: items_block.default.primary.events[].text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;
}

/**
 * Item in *ItemsBlock → Default → Primary → awards*
 */
export interface ItemsBlockSliceDefaultPrimaryAwardsItem {
  /**
   * text field in *ItemsBlock → Default → Primary → awards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: items_block.default.primary.awards[].text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;
}

/**
 * Primary content in *ItemsBlock → Default → Primary*
 */
export interface ItemsBlockSliceDefaultPrimary {
  /**
   * publication text field in *ItemsBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: items_block.default.primary.publication_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  publication_text: prismic.KeyTextField;

  /**
   * publications field in *ItemsBlock → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: items_block.default.primary.publications[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  publications: prismic.GroupField<
    Simplify<ItemsBlockSliceDefaultPrimaryPublicationsItem>
  >;

  /**
   * events title field in *ItemsBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: items_block.default.primary.events_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  events_title: prismic.KeyTextField;

  /**
   * events field in *ItemsBlock → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: items_block.default.primary.events[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  events: prismic.GroupField<Simplify<ItemsBlockSliceDefaultPrimaryEventsItem>>;

  /**
   * awards text field in *ItemsBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: items_block.default.primary.awards_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  awards_text: prismic.KeyTextField;

  /**
   * awards field in *ItemsBlock → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: items_block.default.primary.awards[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  awards: prismic.GroupField<Simplify<ItemsBlockSliceDefaultPrimaryAwardsItem>>;
}

/**
 * Default variation for ItemsBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ItemsBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ItemsBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ItemsBlock*
 */
type ItemsBlockSliceVariation = ItemsBlockSliceDefault;

/**
 * ItemsBlock Shared Slice
 *
 * - **API ID**: `items_block`
 * - **Description**: ItemsBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ItemsBlockSlice = prismic.SharedSlice<
  "items_block",
  ItemsBlockSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutDocument,
      AboutDocumentData,
      AboutDocumentDataSlicesSlice,
      PublicationsDocument,
      PublicationsDocumentData,
      PublicationsDocumentDataPublicationsItem,
      AllDocumentTypes,
      ItemsBlockSlice,
      ItemsBlockSliceDefaultPrimaryPublicationsItem,
      ItemsBlockSliceDefaultPrimaryEventsItem,
      ItemsBlockSliceDefaultPrimaryAwardsItem,
      ItemsBlockSliceDefaultPrimary,
      ItemsBlockSliceVariation,
      ItemsBlockSliceDefault,
    };
  }
}
