// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  items_block: dynamic(() => import("./ItemsBlock")),
  stats_block: dynamic(() => import("./StatsBlock")),
};
