// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_core_lab: dynamic(() => import("./AboutCoreLab")),
  about_hero_block: dynamic(() => import("./AboutHeroBlock")),
  about_me_block: dynamic(() => import("./AboutMeBlock")),
  courses_block: dynamic(() => import("./CoursesBlock")),
  current_student_block: dynamic(() => import("./CurrentStudentBlock")),
  etcr_hero_block: dynamic(() => import("./EtcrHeroBlock")),
  etcr_text_image_block: dynamic(() => import("./EtcrTextImageBlock")),
  gallery_block: dynamic(() => import("./GalleryBlock")),
  hero_block: dynamic(() => import("./HeroBlock")),
  home_hero_block: dynamic(() => import("./HomeHeroBlock")),
  image_slider: dynamic(() => import("./ImageSlider")),
  items_block: dynamic(() => import("./ItemsBlock")),
  past_students_block: dynamic(() => import("./PastStudentsBlock")),
  services_block: dynamic(() => import("./ServicesBlock")),
  stats_block: dynamic(() => import("./StatsBlock")),
  student_hero_block: dynamic(() => import("./StudentHeroBlock")),
  teaching_hero_block: dynamic(() => import("./TeachingHeroBlock")),
};
